title: Sai Pridhvi Pinninti
description: Data Scientist | Python, SQL, AWS, Snowflake, MATLAB
url: "https://pridhvipinninti.github.io"
author:
  name: Sai Pridhvi Pinninti
  email: saipridhvipinninti@gmail.com
  github: https://github.com/pridhvipinninti
  linkedin: https://www.linkedin.com/in/pridhvi-pinninti/
remote_theme: jivancic/minimal-mistakes
plugins:
  - jekyll-remote-theme


sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css
