title: Sai Pridhvi Pinninti
description: Data Scientist | Python, SQL, AWS, Snowflake, MATLAB
url: "https://pridhvipinninti.github.io"
author:
  name: Sai Pridhvi Pinninti
  email: saipridhvipinninti@gmail.com
  github: https://github.com/pridhvipinninti
  linkedin: https://www.linkedin.com/in/pridhvi-pinninti/
remote_theme: pages-themes/cayman@v0.2.0


sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css
